# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
vars = {}
  
  
driver.get("https://maildrop.cc/inbox/?mailbox=upset.anteater3994")
driver.set_window_size(1536, 866)
driver.find_element(By.CSS_SELECTOR, ".order-2 > .ml-2").click()
driver.find_element(By.CSS_SELECTOR, ".order-2").click()
driver.find_element(By.CSS_SELECTOR, ".order-2 > .ml-2").click()
  
