# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAD():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aD(self):
    self.driver.get("https://commerce.adobe.com/business-trial/sign-up?items%5B0%5D%5Bid%5D=D88531E5A20E1D8D87D1E1308E6F4ADE&cli=adobe_com_cct&lang=en&co=IL&promoid=RBS7NL39&mv=other%2Caffiliate&mv2=red&sid=78654bee-de13-463f-89bb-a900cc257fe2")
    self.driver.set_window_size(1202, 827)
    self.driver.find_element(By.ID, "EmailInputField__emailField__ER7HO").click()
    self.driver.find_element(By.ID, "EmailInputField__emailField__ER7HO").send_keys("EWRGEWRGWERG")
    self.driver.find_element(By.ID, "firstNameField").click()
    self.driver.find_element(By.ID, "firstNameField").send_keys("EWRGERGW")
    self.driver.find_element(By.ID, "lastNameField").click()
    self.driver.find_element(By.ID, "lastNameField").send_keys("WERGERWG")
    self.driver.find_element(By.ID, "companyNameField").click()
    self.driver.find_element(By.ID, "companyNameField").send_keys("WERGERG")
    self.driver.find_element(By.ID, "companySizeField-value").click()
    element = self.driver.find_element(By.ID, "companySizeField-value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".spectrum-Menu-item:nth-child(1) > .spectrum-Menu-itemLabel").click()
    self.driver.find_element(By.ID, "countryField-value").click()
    self.driver.find_element(By.ID, "countryField-value").click()
    element = self.driver.find_element(By.ID, "countryField-value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".spectrum-Menu-item:nth-child(35) > .spectrum-Menu-itemLabel").click()
    self.driver.find_element(By.ID, "countryField-value").click()
    element = self.driver.find_element(By.ID, "countryField-value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "countryField-value").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spectrum-Menu-item:nth-child(37) > .spectrum-Menu-itemLabel").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-selected > .spectrum-Menu-itemLabel").click()
    self.driver.find_element(By.ID, "businessPhoneField").click()
    self.driver.find_element(By.ID, "ActionPopUp__actionButton__1LjaP").click()
  
